# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 669eb4665ce1669a4ab1ddcfb3e5b931835666de38c23b76f28f987d4dfa5ce40bc4890d6be9c773c5eebe8c1116dc7c48ba08b4e05a545db89eae2bd731cb5b

test:
  secret_key_base: 11750dfd92f79254447ffd2d4b6319583b00080e689969d376e9adea1e78b906843dd2a3df2a04bc9686e2ccb1e27efd27adff1ebc5b1faf712b029eda0a3226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
